### ISSUE TITLE
Add an Emoji Picker for Chat Messages

### ISSUE THREAD

**Issue by AitijhyaModak** [AitijhyaModak/chat-app#1]
## 📝 Objective 
Enhance the chat functionality by adding an emoji picker to allow users to insert emojis into their messages. This feature should be implemented as a button next to the message text box, which opens a pop-up displaying a set of emojis. The user can choose an emoji, which will be inserted into the message.

## 🎯 Tasks
- Add a button or icon next to the message text box that triggers the emoji picker.

## 📋 Requirements
- The emoji picker when clicked should display a list of emojis.
- When an emoji is clicked, it should be inserted into the message input field at the current cursor position.
- The emojis should be displayed using an emoji picker library like emoji-mart, react-emoji-picker, etc.
- The emoji picker should close automatically once an emoji is selected.

## 📋 Skills Required
- Tailwind CSS.
- ReactJs or NextJs.

## 📂 Files to Update
- app/components/ChatBox.js

## ✅ Acceptance Criteria
- The Emoji Picker must work both in mobile and computer alike.
- Emojis must be sent as part of text message without requiring any kind of special encoding.

  
## 🔥 Bonus (optional)
- Add support for search functionality within the emoji picker to quickly find emojis by name.

**Comment by sinpea** [comment]
Hi, I am interested in working on this issue.

**Comment by sinpea** [comment]
Hi, I am interested in working on this issue.
