### ISSUE TITLE
Add Message Timestamps

### ISSUE THREAD

**Issue by AitijhyaModak** [AitijhyaModak/chat-app#4]
## 📝 Objective
Improve the chat interface by adding message timestamps.

## 🎯 Tasks
   - Add a timestamp next to each message indicating when it was sent / received (e.g., “10:30 AM” or “12:45 PM”)

## 📃 Requirements
- The timestamp should be placed at the **bottom-right** or **top-right** corner of each message bubble.
- The timestamp should have a **lighter font color** to differentiate it from the message content.
- Do not include date in the timestamp (only time).

## 📋 Skills Required
- TailwindCss
- ReactJs or NextJs
- Javascript

## 📂 Files to Update
- app/components/MessageList.js

## ✅ Acceptance Criteria
- The timestamp must be clearly readable and distinguishable from the message contents.

## 🔥Bonus (optional)
- Change the existing color palette of the chat messages to make the design more visually appealing (Do not change the background colors).

**Comment by iOmKumar30** [comment]
@AitijhyaModak 
Kindly review the PR #10 for this issue.
