### ISSUE TITLE
Allow Users to Send Images as Messages

### ISSUE THREAD

**Issue by AitijhyaModak** [AitijhyaModak/chat-app#5]
## 📝 Objective
Enhance the chat experience by allowing users to send **images** in addition to text messages. Users should be able to upload images from their device and share them in the chat. The images should be displayed in the chat interface as inline images with appropriate formatting and visual styling.

## 🎯 Tasks
1. **Image Upload Interface:**
   - Provide an **upload button** or drag-and-drop area that allows users to select and upload image files.
   - Allow users to select an image file from their local device.
   
2. **Image Styling:**
   - Once uploaded, display the image directly in the chat window as an inline image.
   - The image should be styled in a way that it doesn’t disrupt the chat layout.
   - Ensure the image is displayed with a **border-radius** or **rounded corners** for better styling.

3. **Backend & File Storage:**
   - Upload the image to a cloud storage solution or backend server (e.g. **Cloudinary** free plan).
   - Use the cloud service's API to handle the image upload, storage, and retrieval. 
   - Send the image URL as part of the chat message.

## 📋 Skills Required
- NextJs (very basic understanding)
- TailwindCss
- You will have to read PusherJs docs
- Understanding of Cloudinary

## 📂 Files to Update
- app/components/ChatBox.js
- app/components/MessageList.js
- api/message/send/route.js
- might need to create new routes

## ✅ Acceptance Criteria
- Tasks 1 and 3 must be completed for acceptance.

## 🔥Bonus (optional)
   - **Image captions**: Allow users to add a caption when they upload an image.
   - **Image editing**: Allow users to crop the image before sending.
   - Display a **preview** of the image before it’s sent, so users can confirm they are uploading the correct file.
   -  Allow user to be able to click on the image to **view it in full screen**.

**Comment by iOmKumar30** [comment]
I would like to work on this feature.
