### ISSUE TITLE
Change Chat Box Color

### ISSUE THREAD

**Issue by AitijhyaModak** [AitijhyaModak/chat-app#8]
## 📝 Objective
Improve visual appeal of the application by changing the chat box color to a lighter shade of yellow (for incoming messages).

## 🎯 Tasks
- Change the incoming chats color to a lighter shade of yellow

## 📋 Skills Required
- JSX / HTML
- TailwindCss

## 📂 Files to Update
- app/components/MessageList.js (inside 'Message' function)

**Comment by Mayank9207** [comment]
I would like to work over this issue
