### ISSUE TITLE
Unable to see send messages which send previously after page reload

### ISSUE THREAD

**Issue by DeepakVishwakarma123** [AitijhyaModak/chat-app#9]
as i send message the data is going to server and it showing me in ui in same room but as i refresh the page then there is no message displaying in same room i sawed network tab there is the get request is send but it just returning some data like a [object,object] but it is can,t showing some data there as i feel while using it for adding some features.
<img width="960" alt="send message" src="https://github.com/user-attachments/assets/69c5f6c1-65c7-41ca-b16b-84618313c5e8">
<img width="644" alt="sended data" src="https://github.com/user-attachments/assets/9f206f2e-3392-47d8-9b7a-9f34d41d5279">
<img width="960" alt="after page refresh" src="https://github.com/user-attachments/assets/f6f60b8c-764e-412d-8fc7-aa7ba56e5b1f">
<img width="317" alt="response after page reload in get" src="https://github.com/user-attachments/assets/48675fd2-88e8-42d4-a8f9-4075147bd97d">

images purpose explained here
first is send message image
second is send data to the server image
third after page refresh image
fourth response getting from server through get request image

**Comment by AitijhyaModak** [comment]
I appreciate you raising this issue. First I would like to point out that it is clearly stated in the ```README.md``` that this project is open to contribution only for students from IIESTS. 

Regarding the issue you've raised, I would like to point out that it is clearly stated in the ```README.md``` that messages are not stored in the database, and hence, there is no way to reload messages after a page refresh. While your point is valid, implementing the ability to store messages in the database is outside the current scope of the project.

Hence, I will be closing this issue.

**Comment by DeepakVishwakarma123** [comment]
Okk 👍
